### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [WojciechMula/graphics#1]
Hello, under what license(s) is this project released under ? I would like learn how to use tkinter for advanced GUI applications and this project seems like a wonderful resource. Thank-you.

**Comment by WojciechMula** [comment]
Maybe some files has license terms, but you may assume that the license of everything is simplified BSD - so fell free to use. :) I'll add a license file later.

**Comment by WojciechMula** [comment]
Added explicit LICENSE - BSD 2-claused
